UtnSofftek.CriptoMoneda/Models/Cuenta.cs
using System.ComponentModel.DataAnnotations;

namespace UtnSofftek.CriptoMoneda.Models
{
    public class Cuenta
    {
        public int IdCuenta { get; set; }
        public decimal Saldo { get; set; }
        [Required]  
        public string? Tipo { get; set; }
        public int IdCliente { get; set; }
    }
}

UtnSofftek.CriptoMoneda/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Mvc;
using UtnSofftek.CriptoMoneda.Datos;
using UtnSofftek.CriptoMoneda.Models;

namespace UtnSofftek.CriptoMoneda.Controllers
{
    public class CuentasController : Controller
    {
        CuentaDatos cuentaDatos = new CuentaDatos();
        public IActionResult Lista()
        {
            List<FiduciariaModel>? listaFiduciaria = new List<FiduciariaModel>();
            List<CriptoModel>? listaCripto = new List<CriptoModel>();
            listaFiduciaria = cuentaDatos.ListarFiduciaria(1);
            listaCripto = cuentaDatos.ListarCripto(1);
            ListaCuentaModel listaCuentas = new(listaFiduciaria, listaCripto);
            return View(listaCuentas);
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(CuentasModel cuentas)

        {
            if (cuentas.Tipo != null)
            {
                if (cuentas.Tipo == "ARG" || cuentas.Tipo == "USD")
                {
                    string cbu = "05480000" + (string)DateTime.Now.ToString("yyyyMMddHHmmss");
                    FiduciariaModel fiduciariaModel = new FiduciariaModel();
                    fiduciariaModel.Saldo = 0;
                    fiduciariaModel.Tipo = cuentas.Tipo;
                    fiduciariaModel.IdCliente = 1;
                    fiduciariaModel.CBU = cbu;
                    fiduciariaModel.Alias = GenerarAlias();
                    fiduciariaModel.NroCuenta = Convert.ToInt32(DateTime.Now.ToString("ddHHmmss"));

                    var respuesta = cuentaDatos.CrearCuentaFiduciaria(fiduciariaModel);
                    if (respuesta)
                    {
                        return RedirectToAction("Lista");
                    }
                }
                else
                {
                    CriptoModel criptoModel = new CriptoModel();
                    criptoModel.Saldo = 0;
                    criptoModel.Tipo = cuentas.Tipo;
                    criptoModel.IdCliente = 1;
                    criptoModel.Uuid = (string)DateTime.Now.ToString("yyyyMMddHHmmss");

                    var respuesta = cuentaDatos.CrearCuentaCripto(criptoModel);
                    if (respuesta)
                    {
                        return RedirectToAction("Lista");
                    }
                }
            }
            return View();
        }

        public IActionResult DatosCuentas(int id)
        {
            Cuenta cuenta = cuentaDatos.ObtenerCuenta(id);
            CuentasModel cuentas = new CuentasModel();
            if (cuenta.Tipo == "ARG" || cuenta.Tipo == "USD")
            {
                cuentas.Fiduciaria = (FiduciariaModel)cuenta;
            }
            else
            {
                cuentas.Cripto = (CriptoModel)cuenta;

            }
            return View(cuentas);
        }

        public IActionResult Depositar(int id)
        {
            CuentasModel cuentas = new CuentasModel();
            cuentas.Fiduciaria = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            return View(cuentas);
        }

        [HttpPost]
        public IActionResult Depositar(FiduciariaModel fiduciaria)
        {
            FiduciariaModel fiduModel = (FiduciariaModel)cuentaDatos.ObtenerCuenta(fiduciaria.IdCuenta);
            decimal newSaldo = fiduModel.Saldo;
            if (fiduciaria.Saldo > 0)
            {
                decimal conversion = 0;
                if (fiduciaria.Tipo == "ARG")
                {
                    newSaldo += fiduciaria.Saldo;
                    conversion = fiduciaria.Saldo;
                }
                if (fiduciaria.Tipo == "USD")
                {
                    newSaldo += (fiduciaria.Saldo / (decimal)208.88d);
                    conversion = (fiduciaria.Saldo / (decimal)208.88d);
                }
                var respuesta = cuentaDatos.ActualizarSaldo(newSaldo, fiduciaria.IdCuenta);
                if (respuesta)
                {
                    HistorialModel historial = new HistorialModel();
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = fiduciaria.IdCuenta;
                    historial.Monto = conversion;
                    historial.Tipo = "Deposito";
                    cuentaDatos.CrearHistorial(historial);
                    return RedirectToAction("Lista");
                }
            }
            return View();
        }

        public IActionResult Extraer(int id)
        {
            CuentasModel cuentas = new CuentasModel();
            cuentas.Fiduciaria = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            return View(cuentas);
        }
        [HttpPost]
        public IActionResult Extraer(FiduciariaModel fiduciaria)
        {
            FiduciariaModel fiduModel = (FiduciariaModel)cuentaDatos.ObtenerCuenta(fiduciaria.IdCuenta);
            decimal newSaldo = fiduModel.Saldo;
            if (fiduciaria.Saldo <= fiduModel.Saldo)
            {
                decimal conversion = 0;
                if (fiduciaria.Tipo == "ARG")
                {
                    conversion = fiduciaria.Saldo;
                    newSaldo -= conversion;
                }
                if (fiduciaria.Tipo == "USD")
                {
                    conversion = (fiduciaria.Saldo / (decimal)208.88d);
                    newSaldo -= conversion;
                }
                var respuesta = cuentaDatos.ActualizarSaldo(newSaldo, fiduciaria.IdCuenta);
                if (respuesta)
                {
                    HistorialModel historial = new HistorialModel();
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = fiduciaria.IdCuenta;
                    historial.Monto = conversion;
                    historial.Tipo = "Extraccion";
                    cuentaDatos.CrearHistorial(historial);
                    return RedirectToAction("Lista");
                }
            }
            return View();
        }

        public IActionResult TransferirFiducaria(int id)
        {
            FiduciariaModel cuentaOrigen = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            TransferenciaModel transfeModel = new TransferenciaModel();
            transfeModel.ListaFiduciarias = cuentaDatos.ListarFiduciaria(1);
            transfeModel.ListaCripto = cuentaDatos.ListarCripto(1);
            transfeModel.FiduOrigen = cuentaOrigen;

            return View(transfeModel);
        }

        [HttpPost]
        public IActionResult TransferirFiducaria(TransferenciaModel transfeModel)
        {
            //VARIABLES
            var cuentaOrigen = cuentaDatos.ObtenerCuenta(transfeModel.FiduOrigen.IdCuenta);
            string[] datos = transfeModel.IdCuentaDestino.Split(',');
            int idCuentaDestino = Convert.ToInt32(datos[0]);
            string tipoOrigen = cuentaOrigen.Tipo;
            string tipoDestino = datos[1];
            var cuentaDestino = cuentaDatos.ObtenerCuenta(idCuentaDestino);
            decimal conversion = 0;
            decimal saldoOrigen = cuentaOrigen.Saldo;
            decimal saldoDestino = cuentaDestino.Saldo;

            if (saldoOrigen >= transfeModel.Saldo && transfeModel.Saldo != 0)
            {
                switch (tipoOrigen)
                {
                    case "ARG":
                        if (tipoDestino == "ARG")
                        {
                            conversion = transfeModel.Saldo;
                            saldoOrigen -= conversion;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "USD")
                        {
                            conversion = (transfeModel.Saldo * (decimal)0.004787d); //(207) 0,990909
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "BTC")
                        {
                            conversion = transfeModel.Saldo * (decimal)0.004787d; //(207) 0,990909
                            conversion = (conversion * (decimal)0.000032d); //0,000031
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        break;
                    case "USD":
                        if (tipoDestino == "ARG")
                        {
                            conversion = (transfeModel.Saldo * (decimal)208.88d); // (1) 208,88
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "USD")
                        {
                            conversion = transfeModel.Saldo;
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "BTC")
                        {
                            conversion = (transfeModel.Saldo * (decimal)0.000032d); // (5) 0.00016
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        break;

                }
                //Actualizar Saldo en Origen
                var respuesta = cuentaDatos.ActualizarSaldo(saldoOrigen, cuentaOrigen.IdCuenta);
                HistorialModel historial = new HistorialModel();
                if (respuesta)
                {
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = cuentaOrigen.IdCuenta;
                    historial.Monto = transfeModel.Saldo;
                    historial.Tipo = "Transf. Realizada";
                    cuentaDatos.CrearHistorial(historial);
                }

UtnSofftek.CriptoMoneda/Controllers/HistorialController.cs
using Microsoft.AspNetCore.Mvc;
using UtnSofftek.CriptoMoneda.Datos;
using UtnSofftek.CriptoMoneda.Models;

namespace UtnSofftek.CriptoMoneda.Controllers
{
    public class HistorialController : Controller
    {
        CuentaDatos cuentasDatos = new CuentaDatos();
        public IActionResult Listar(int id)
        {
            List<HistorialModel> listaHistoria = cuentasDatos.ListarHistorial(id);
            return View(listaHistoria);
        }
    }
}

UtnSofftek.CriptoMoneda/Views/Cuentas/Crear.cshtml
@model CuentasModel;
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="text-center">Crear Cuenta</h2>
    </div>
    <form asp-action="Crear" asp-controller="Cuenta" method="post">
        <div class="card-body">
            <div class="mb-3">
                <label class="form-label">Seleccione el tipo de cuenta: </label>
                <select asp-for="Tipo" class="form-select">
                    <option value="ARG">En Pesos (ARG)</option>
                    <option value="USD">En Dólares (USD)</option>
                    <option value="BTC">En Bitcoins (BTC)</option>
                </select>
            </div>

        </div>
        <div class="card-footer">
            <button asp-action="Crear" asp-controller="Cuentas" class="btn btn-primary">Editar Datos</button>
            <a asp-action="Lista" asp-controller="Cuentas" class="btn btn-outline-success">Volver a Lista de Cuentas</a>
        </div>
    </form>
</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/DatosCuentas.cshtml
@model CuentasModel
@{
    ViewData["Title"] = "DatosCuentas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center mt-4">Mis Cuentas</h2>
        </div>
        <div class="card-body">
            @if (Model.Fiduciaria != null)
            {
                @if (Model.Fiduciaria.Tipo == "ARG")
                {
                    <h5 class="card-title">Cuenta en Pesos</h5>
                }
                else
                {
                    <h5 class="card-title">Cuenta en Dolares</h5>
                }
                <p class="card-text">
                    <strong>Nro Cuenta: </strong> @Model.Fiduciaria.NroCuenta
                </p>
                <p class="card-text">
                    <strong>CBU: </strong> @Model.Fiduciaria.CBU
                </p>
                <p class="card-text">
                    <strong>Alias: </strong>@Model.Fiduciaria.Alias
                </p>
                <p class="card-text text-end">
                    <strong>SALDO: </strong> @Model.Fiduciaria.Tipo $@Model.Fiduciaria.Saldo.ToString("0.##")
                </p>
            }
            else
            {
                <h5 class="card-title">Cuenta en BitCoin</h5>
                <p class="card-text">
                    <strong>UUID </strong> @Model.Cripto.Uuid
                </p>
                <p class="card-text text-end">
                    <strong>SALDO: </strong> @Model.Cripto.Tipo $@Model.Cripto.Saldo.ToString("0.######")
                </p>
            }

        </div>
        <div class="card-footer">
            @if (Model.Fiduciaria != null)
            {
                <a asp-action="Depositar"
               asp-controller="Cuentas"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-success d-block my-2">Depositar</a>
                @if (Model.Fiduciaria.Saldo > 0)
                {
                    <a asp-action="Extraer"
               asp-controller="Cuentas"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-primary d-block my-2">Extraer</a>
                    <a asp-action="TransferirFiducaria"
               asp-controller="Cuentas"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-warning d-block my-2">Transferir</a>
                }
                <a asp-action="Listar"
               asp-controller="Historial"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-secondary d-block my-2">Ver Movimientos</a>
            }
            else
            {
                @if (Model.Cripto.Saldo > 0)
                {
                    <a asp-action="TransferirCripto"
                        asp-controller="Cuentas" 
                        asp-route-id=@Model.Cripto.IdCuenta
                        class="btn btn-warning d-block my-2">Transferir</a>
                }
                <a asp-action="Listar"
               asp-controller="Historial"
               asp-route-id=@Model.Cripto.IdCuenta
               class="btn btn-secondary d-block my-2">Ver Movimientos</a>
            }
        </div>
    </div>
</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/Depositar.cshtml
@model CuentasModel
@{
    ViewData["Title"] = "Depositar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="text-center">Crear Cuenta</h2>
    </div>
    <form asp-action="Depositar" asp-controller="Cuenta" method="post">
        <div class="card-body">
            <div class="mb-3">
                <label class="form-label">Seleccione el tipo de cuenta: </label>
                <div class="input-group mb-3">
                    <span class="input-group-text">ARS $</span>
                    <input asp-for=Fiduciaria.Saldo type="number" class="form-control" value=0/>
                </div>
                @if (Model.Fiduciaria.Tipo == "USD")
                {
                    <div class="alert alert-dark">
                        El deposito es en Pesos Argentino y la conversión en dolares se hace automáticamente
                    </div>
                }
            </div>

        </div>
        <div class="card-footer">
            <input asp-for=@Model.Fiduciaria.IdCuenta type="hidden" />
            <input asp-for=@Model.Fiduciaria.Tipo type="hidden" />

            <button asp-action="Depositar"
                    asp-controller="Cuentas"
                    class="btn btn-success">
                Depositar
            </button>
            <a asp-action="DatosCuentas"
               asp-controller="Cuentas"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-outline-danger my-3 d-block">Volver a Detalles de Cuenta</a>
        </div>
    </form>
</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/Extraer.cshtml
@model CuentasModel
@{
    ViewData["Title"] = "Extraer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="text-center">Crear Cuenta</h2>
    </div>
    <form asp-action="Extraer" asp-controller="Cuenta" method="post">
        <div class="card-body">
            <p class="card-text">
                <strong>Saldo Disponible: </strong>@Model.Fiduciaria.Tipo $@Model.Fiduciaria.Saldo.ToString("0.##")
            </p>
            <div class="mb-3">
                <label class="form-label">Ingrese la cantidad </label>
                <div class="input-group mb-3">
                    <span class="input-group-text">ARS $</span>
                    <input asp-for=Fiduciaria.Saldo type="number" class="form-control" value=0 />
                </div>
                @if (Model.Fiduciaria.Tipo == "USD")
                {
                    <div class="alert alert-dark">
                        El deposito es en Pesos Argentino y la conversión en dolares se hace automáticamente
                    </div>
                }
            </div>

        </div>
        <div class="card-footer">
            <input asp-for=@Model.Fiduciaria.IdCuenta type="hidden" />
            <input asp-for=@Model.Fiduciaria.Tipo type="hidden" />

            <button asp-action="Extraer"
                    asp-controller="Cuentas"
                    class="btn btn-primary">
                Extraer
            </button>
            <a asp-action="DatosCuentas"
               asp-controller="Cuentas"
               asp-route-id=@Model.Fiduciaria.IdCuenta
               class="btn btn-outline-danger my-3 d-block">Volver a Detalles de Cuenta</a>
        </div>
    </form>
</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/Lista.cshtml
@model ListaCuentaModel
@{
    ViewData["Title"] = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center mt-4">Mis Cuentas</h2>
<hr>
<div class="row">
    @if (Model.listaCripto != null || Model.listaFiduciarias != null)
    {
        @foreach (var item in Model.listaFiduciarias)
        {
            <div class="col-6 mt-5">
                <div class="card">
                    <div class="card-body">

                        @if (@item.Tipo == "ARG")
                        {
                            <h5 class="card-title">Cuenta en Pesos</h5>
                        }
                        else
                        {
                            <h5 class="card-title">Cuenta en Dolares</h5>
                        }
                        <p class="card-text">
                            <strong>Nro Cuenta: </strong>@item.NroCuenta
                        </p>
                        <p class="card-text">
                            <strong>CBU: </strong>@item.CBU
                        </p>
                        <p class="card-text">
                            <strong>Alias: </strong>@item.Alias
                        </p>
                        <p class="card-text text-end">
                            <strong>SALDO: </strong> @item.Tipo $@item.Saldo.ToString("0.##")
                        </p>
                    </div>
                    <div class="card-footer">
                        <a asp-action="DatosCuentas"
                   asp-controller="Cuentas"
                   asp-route-id=@item.IdCuenta
                   class="btn btn-primary d-block my-2">
                            Ver Cuenta
                        </a>
                    </div>
                </div>
            </div>
        }
        @foreach (var item in Model.listaCripto)
        {
            <div class="col-6 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cuenta en BitCoin</h5>
                        <p class="card-text">
                            <strong>UUID: </strong> @item.Uuid
                        </p>
                        <p class="card-text text-end">
                            <strong>SALDO: </strong> BTC $@item.Saldo.ToString("0.######")
                        </p>
                    </div>
                    <div class="card-footer">
                        <a asp-action="DatosCuentas"
                   asp-controller="Cuentas"
                   asp-route-id=@item.IdCuenta
                   class="btn btn-primary d-block my-2">
                            Ver Cuenta
                        </a>
                    </div>
                </div>
            </div>
        }
    }
    <div class="col-6 mt-2">
        <div class="agregar-cuenta">
            <a asp-action="Crear" asp-controller="Cuentas" class="btn btn-outline-success">+</a>
        </div>
    </div>

</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/TransferirCripto.cshtml
@model TransferenciaModel
@{
    ViewData["Title"] = "TransferirCripto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="text-center">Transferir | Uui: @Model.CriptoOrigen.Uuid</h2>
    </div>
    <form asp-action="TransferirCripto" asp-controller="Cuenta" method="post">
        <div class="card-body">
            <p class="card-text">
                <strong>Saldo Disponible: </strong>@Model.CriptoOrigen.Tipo <span>$</span>@Model.CriptoOrigen.Saldo.ToString("0.##")
            </p>
            <div class="mb-3">
                <label class="form-label">Ingrese la cuenta Destino </label>
                <select asp-for=IdCuentaDestino class="form-select">
                    @if (Model.ListaFiduciarias != null)
                    {
                        @foreach (var item in Model.ListaFiduciarias)
                        {

                            <option value="@item.IdCuenta,@item.Tipo">
                                NroCuenta: @item.NroCuenta | <strong>@item.Tipo $@item.Saldo.ToString("0.##")</strong>
                            </option>

                        }
                    }
                    @if (Model.ListaCripto != null)
                    {
                        @foreach (var item in Model.ListaCripto)
                        {
                            @if (Model.CriptoOrigen.IdCuenta != item.IdCuenta)
                            {
                                <option value="@item.IdCuenta,@item.Tipo">
                                    Uuid: @item.Uuid | <strong>@item.Tipo $@item.Saldo.ToString("0.0000##")</strong>
                                </option>
                            }
                        }
                    }
                    }
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">Saldo a Transferir </label>
                <div class="input-group mb-3">
                    <span class="input-group-text">@Model.CriptoOrigen.Tipo $</span>
                    <input asp-for=Saldo type="number" class="form-control" value=0 />
                </div>
            </div>

        </div>
        <div class="card-footer">
            <input asp-for=@Model.CriptoOrigen.IdCuenta type="hidden" />
            <input asp-for=@Model.CriptoOrigen.Tipo type="hidden" />

            <button asp-action="TransferirCripto"
                    asp-controller="Cuentas"
                    class="btn btn-warning">
                Transferir
            </button>
            <a asp-action="DatosCuentas"
               asp-controller="Cuentas"
               asp-route-id=@Model.CriptoOrigen.IdCuenta
               class="btn btn-outline-danger my-3 d-block">Volver a Detalles de Cuenta</a>
        </div>
    </form>
</div>

UtnSofftek.CriptoMoneda/Views/Cuentas/TransferirFiducaria.cshtml
@model TransferenciaModel
@{
    ViewData["Title"] = "TransferirFiducaria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mt-5">
    <div class="card-header">
        <h2 class="text-center">Transferir | CBU: @Model.FiduOrigen.CBU</h2>
    </div>
    <form asp-action="TransferirFiducaria" asp-controller="Cuenta" method="post">
        <div class="card-body">
            <p class="card-text">
                <strong>Saldo Disponible: </strong>@Model.FiduOrigen.Tipo <span>$</span>@Model.FiduOrigen.Saldo.ToString("0.##")
            </p>
            <div class="mb-3">
                <label class="form-label">Ingrese la cuenta Destino </label>
                <select asp-for=IdCuentaDestino class="form-select">
                    @if (Model.ListaFiduciarias != null)
                    {
                        @foreach (var item in Model.ListaFiduciarias)
                        {
                            @if (Model.FiduOrigen.IdCuenta != item.IdCuenta)
                            {
                                <option value="@item.IdCuenta,@item.Tipo">
                                    NroCuenta: @item.NroCuenta | <strong>@item.Tipo $@item.Saldo.ToString("0.##")</strong>
                                </option>

                            }
                        }
                    }
                    @if (Model.ListaCripto != null)
                    {
                        @foreach (var item in Model.ListaCripto)
                        {
                            <option value="@item.IdCuenta,@item.Tipo">
                                Uuid: @item.Uuid | <strong>@item.Tipo $@item.Saldo.ToString("0.0000##")</strong>
                            </option>
                        }
                    }
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">Saldo a Transferir </label>
                <div class="input-group mb-3">
                    <span class="input-group-text">@Model.FiduOrigen.Tipo $</span>
                    <input asp-for=Saldo type="number" class="form-control" value=0 />
                </div>
            </div>

        </div>
        <div class="card-footer">
            <input asp-for=@Model.FiduOrigen.IdCuenta type="hidden" />
            <input asp-for=@Model.FiduOrigen.Tipo type="hidden" />

            <button asp-action="TransferirFiducaria"
                    asp-controller="Cuentas"
                    class="btn btn-warning">
                Transferir
            </button>
            <a asp-action="DatosCuentas"
               asp-controller="Cuentas"
               asp-route-id=@Model.FiduOrigen.IdCuenta
               class="btn btn-outline-danger my-3 d-block">Volver a Detalles de Cuenta</a>
        </div>
    </form>
</div>