UtnSofftek.CriptoMoneda/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using UtnSofftek.CriptoMoneda.Datos;
using UtnSofftek.CriptoMoneda.Models;

namespace UtnSofftek.CriptoMoneda.Controllers
{
    public class ClienteController : Controller
    {
        ClienteDatos clienteDatos = new ClienteDatos();
        public IActionResult VerDatos()
        {
            ClienteModel cliente = clienteDatos.ObtenerCliente(1);
            return View(cliente);
        }

        public IActionResult Editar(int id)
        {
            ClienteModel cliente = clienteDatos.ObtenerCliente(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Editar(ClienteModel cliente)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var respuesta = clienteDatos.Editar(cliente);
            if (respuesta)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

UtnSofftek.CriptoMoneda/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Mvc;
using UtnSofftek.CriptoMoneda.Datos;
using UtnSofftek.CriptoMoneda.Models;

namespace UtnSofftek.CriptoMoneda.Controllers
{
    public class CuentasController : Controller
    {
        CuentaDatos cuentaDatos = new CuentaDatos();
        public IActionResult Lista()
        {
            List<FiduciariaModel>? listaFiduciaria = new List<FiduciariaModel>();
            List<CriptoModel>? listaCripto = new List<CriptoModel>();
            listaFiduciaria = cuentaDatos.ListarFiduciaria(1);
            listaCripto = cuentaDatos.ListarCripto(1);
            ListaCuentaModel listaCuentas = new(listaFiduciaria, listaCripto);
            return View(listaCuentas);
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(CuentasModel cuentas)

        {
            if (cuentas.Tipo != null)
            {
                if (cuentas.Tipo == "ARG" || cuentas.Tipo == "USD")
                {
                    string cbu = "05480000" + (string)DateTime.Now.ToString("yyyyMMddHHmmss");
                    FiduciariaModel fiduciariaModel = new FiduciariaModel();
                    fiduciariaModel.Saldo = 0;
                    fiduciariaModel.Tipo = cuentas.Tipo;
                    fiduciariaModel.IdCliente = 1;
                    fiduciariaModel.CBU = cbu;
                    fiduciariaModel.Alias = GenerarAlias();
                    fiduciariaModel.NroCuenta = Convert.ToInt32(DateTime.Now.ToString("ddHHmmss"));

                    var respuesta = cuentaDatos.CrearCuentaFiduciaria(fiduciariaModel);
                    if (respuesta)
                    {
                        return RedirectToAction("Lista");
                    }
                }
                else
                {
                    CriptoModel criptoModel = new CriptoModel();
                    criptoModel.Saldo = 0;
                    criptoModel.Tipo = cuentas.Tipo;
                    criptoModel.IdCliente = 1;
                    criptoModel.Uuid = (string)DateTime.Now.ToString("yyyyMMddHHmmss");

                    var respuesta = cuentaDatos.CrearCuentaCripto(criptoModel);
                    if (respuesta)
                    {
                        return RedirectToAction("Lista");
                    }
                }
            }
            return View();
        }

        public IActionResult DatosCuentas(int id)
        {
            Cuenta cuenta = cuentaDatos.ObtenerCuenta(id);
            CuentasModel cuentas = new CuentasModel();
            if (cuenta.Tipo == "ARG" || cuenta.Tipo == "USD")
            {
                cuentas.Fiduciaria = (FiduciariaModel)cuenta;
            }
            else
            {
                cuentas.Cripto = (CriptoModel)cuenta;

            }
            return View(cuentas);
        }

        public IActionResult Depositar(int id)
        {
            CuentasModel cuentas = new CuentasModel();
            cuentas.Fiduciaria = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            return View(cuentas);
        }

        [HttpPost]
        public IActionResult Depositar(FiduciariaModel fiduciaria)
        {
            FiduciariaModel fiduModel = (FiduciariaModel)cuentaDatos.ObtenerCuenta(fiduciaria.IdCuenta);
            decimal newSaldo = fiduModel.Saldo;
            if (fiduciaria.Saldo > 0)
            {
                decimal conversion = 0;
                if (fiduciaria.Tipo == "ARG")
                {
                    newSaldo += fiduciaria.Saldo;
                    conversion = fiduciaria.Saldo;
                }
                if (fiduciaria.Tipo == "USD")
                {
                    newSaldo += (fiduciaria.Saldo / (decimal)208.88d);
                    conversion = (fiduciaria.Saldo / (decimal)208.88d);
                }
                var respuesta = cuentaDatos.ActualizarSaldo(newSaldo, fiduciaria.IdCuenta);
                if (respuesta)
                {
                    HistorialModel historial = new HistorialModel();
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = fiduciaria.IdCuenta;
                    historial.Monto = conversion;
                    historial.Tipo = "Deposito";
                    cuentaDatos.CrearHistorial(historial);
                    return RedirectToAction("Lista");
                }
            }
            return View();
        }

        public IActionResult Extraer(int id)
        {
            CuentasModel cuentas = new CuentasModel();
            cuentas.Fiduciaria = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            return View(cuentas);
        }
        [HttpPost]
        public IActionResult Extraer(FiduciariaModel fiduciaria)
        {
            FiduciariaModel fiduModel = (FiduciariaModel)cuentaDatos.ObtenerCuenta(fiduciaria.IdCuenta);
            decimal newSaldo = fiduModel.Saldo;
            if (fiduciaria.Saldo <= fiduModel.Saldo)
            {
                decimal conversion = 0;
                if (fiduciaria.Tipo == "ARG")
                {
                    conversion = fiduciaria.Saldo;
                    newSaldo -= conversion;
                }
                if (fiduciaria.Tipo == "USD")
                {
                    conversion = (fiduciaria.Saldo / (decimal)208.88d);
                    newSaldo -= conversion;
                }
                var respuesta = cuentaDatos.ActualizarSaldo(newSaldo, fiduciaria.IdCuenta);
                if (respuesta)
                {
                    HistorialModel historial = new HistorialModel();
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = fiduciaria.IdCuenta;
                    historial.Monto = conversion;
                    historial.Tipo = "Extraccion";
                    cuentaDatos.CrearHistorial(historial);
                    return RedirectToAction("Lista");
                }
            }
            return View();
        }

        public IActionResult TransferirFiducaria(int id)
        {
            FiduciariaModel cuentaOrigen = (FiduciariaModel)cuentaDatos.ObtenerCuenta(id);
            TransferenciaModel transfeModel = new TransferenciaModel();
            transfeModel.ListaFiduciarias = cuentaDatos.ListarFiduciaria(1);
            transfeModel.ListaCripto = cuentaDatos.ListarCripto(1);
            transfeModel.FiduOrigen = cuentaOrigen;

            return View(transfeModel);
        }

        [HttpPost]
        public IActionResult TransferirFiducaria(TransferenciaModel transfeModel)
        {
            //VARIABLES
            var cuentaOrigen = cuentaDatos.ObtenerCuenta(transfeModel.FiduOrigen.IdCuenta);
            string[] datos = transfeModel.IdCuentaDestino.Split(',');
            int idCuentaDestino = Convert.ToInt32(datos[0]);
            string tipoOrigen = cuentaOrigen.Tipo;
            string tipoDestino = datos[1];
            var cuentaDestino = cuentaDatos.ObtenerCuenta(idCuentaDestino);
            decimal conversion = 0;
            decimal saldoOrigen = cuentaOrigen.Saldo;
            decimal saldoDestino = cuentaDestino.Saldo;

            if (saldoOrigen >= transfeModel.Saldo && transfeModel.Saldo != 0)
            {
                switch (tipoOrigen)
                {
                    case "ARG":
                        if (tipoDestino == "ARG")
                        {
                            conversion = transfeModel.Saldo;
                            saldoOrigen -= conversion;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "USD")
                        {
                            conversion = (transfeModel.Saldo * (decimal)0.004787d); //(207) 0,990909
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "BTC")
                        {
                            conversion = transfeModel.Saldo * (decimal)0.004787d; //(207) 0,990909
                            conversion = (conversion * (decimal)0.000032d); //0,000031
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        break;
                    case "USD":
                        if (tipoDestino == "ARG")
                        {
                            conversion = (transfeModel.Saldo * (decimal)208.88d); // (1) 208,88
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "USD")
                        {
                            conversion = transfeModel.Saldo;
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        if (tipoDestino == "BTC")
                        {
                            conversion = (transfeModel.Saldo * (decimal)0.000032d); // (5) 0.00016
                            saldoOrigen -= transfeModel.Saldo;
                            saldoDestino += conversion;
                        }
                        break;

                }
                //Actualizar Saldo en Origen
                var respuesta = cuentaDatos.ActualizarSaldo(saldoOrigen, cuentaOrigen.IdCuenta);
                HistorialModel historial = new HistorialModel();
                if (respuesta)
                {
                    historial.Fecha = DateTime.Now;
                    historial.IdCuenta = cuentaOrigen.IdCuenta;
                    historial.Monto = transfeModel.Saldo;
                    historial.Tipo = "Transf. Realizada";
                    cuentaDatos.CrearHistorial(historial);
                }

UtnSofftek.CriptoMoneda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UtnSofftek.CriptoMoneda</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="css/normalize.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UtnSofftek.CriptoMoneda.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="contenido">
        <div class="sidebar">
            <div class="menu-info">
                <ul class="menu">
                    <a asp-action="Index" asp-controller="Home">
                    <li>Inicio</li></a>
                    <a asp-action="VerDatos" asp-controller="Cliente">
                    <li>Datos Personales</li></a>
                    <a asp-action="Lista" asp-controller="Cuentas">
                    <li>Cuentas</li></a>
                </ul>
                <ul class="info-visas">
                    <li>CONVERSIÓN</li>
                    <li>
                        <small>
                            <img src="/img/argentina.png" alt="ARG"> ARG $208,88 =
                            <img src="/img/united-states.png" alt="USD">  U$D 1
                        </small>
                    </li>
                    <li>
                        <small>
                            <img src="/img/argentina.png" alt="ARG"> ARG $6.516.972,448 =
                            <img src="/img/bitcoin.png" alt="BTC">  BTC $1
                        </small>
                    </li>
                    <li>
                        <small>
                            <img src="/img/united-states.png" alt="USD"> U$D 31.199,60 =
                            <img src="/img/bitcoin.png" alt="BTC">  BTC $1
                        </small>
                    </li>
                    <li>
                        <small>
                            <img src="/img/united-states.png" alt="USD"> U$D 1 =
                            <img src="/img/bitcoin.png" alt="BTC">  BTC $0,000032
                        </small>
                    </li>
                </ul>
            </div>
        </div>
        <div class="informacion">
            <header>
                <nav class="navbar navbar-expand-lg">
                    <div class="container-fluid">
                        <div class="collapse navbar-collapse p-4"
                             id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active"
                                       aria-current="page"
                                       href="#"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <!-- CONTENIDO -->
            <main class="container">
                @RenderBody()
            </main>
            <!-- FIN CONTENIDO -->
            <footer>
                <p>Diseñado por David Omar Ghiano&copy;</p>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>